### PR TITLE
DE - German Translation

### PR DESCRIPTION
**Pull request by ModeratorPS**
Deutsche Übersetzung

### CODE REVIEW

**Comment by bigtreetech** [comment]
Looks like there are errors in the file:

image

**Comment by ModeratorPS** [comment]
Which file contains the correct formatting with the number of lines? (i.e. which ones must be left blank)

**Comment by bigtreetech** [comment]
The error always tells which line is the problem.

image

**Comment by bigtreetech** [comment]
I am searching through your file locally to investigate what the script is unhappy with. Give me a sec.

**Comment by bigtreetech** [comment]
Each one of your lines appears to start with the ASCII char 0xA0 which is a non-breaking space. Line 25 does not and so the yaml interpreter gets confused. For pure and clean yaml, each indentation should use a standard ASCII space character. VSCODE reveals the issue quite quickly. You could try to search for all of those chars and replace them in one action.

image

**Comment by bigtreetech** [comment]
This is what the template file looks like:

image

**Comment by bigtreetech** [comment]
YAML needs spaces for indentation. Previously you were using 0xA0 as a space character which is wrong since it is not the standard space which is 0x20. Now it is using TAB but it should just be double space (double 0x20).

**Comment by bigtreetech** [comment]
It seems like there are more 0xA0 characters all through the file which are going to cause errors. Not sure what editor you are using but it has put these strange characters there. I suggest VSCODE.

image

**Comment by ModeratorPS** [comment]
> ggest VSCODE.

I am using VSCode, but the error was in my configuration of the Program. Now it should be fixed

**Comment by bigtreetech** [comment]
Triple space on 452
image

**Comment by bigtreetech** [comment]
Danke ;)

**Pull request merged**
